### ISSUE TITLE
get-url fails against letsencrypt certificates

### ISSUE THREAD

**Issue by pawlbouden** [magnetcoop/buddy-auth.jwt-oidc#1]
Thanks for the library, just FYI I encountered an issue with the http-kit client used which prevented validation of a token served from a server with a letsencrypt ssl certificate:
https://github.com/http-kit/http-kit/issues/334

The workaround mentioned in that ticket of configuring the http client with an :ssl-configurer solved the problem for me:
https://github.com/arctype-co/service/commit/3eada92d9f9af8f18c9722dd670e82527d2709a3

Regards,

Paul

**Comment by iarenaza** [comment]
Hi @pawlbouden,

I'm currently abroad with very limited Internet access, but will have a look at the issue as soon as I go back home in a couple of weeks.

Thanks a lot for your report!

**Comment by iarenaza** [comment]
[http-kit v2.4.0 is out](https://github.com/http-kit/http-kit/releases/tag/v2.4.0) and it includes support for a SNI-capable client. Upgrading the dependency should fix this issue.

**Comment by iarenaza** [comment]
Issue fixed in release 0.9.0.
